name: AVM Mandatory Files Policy
description: This policy will ensure the presence of AVM mandatory files into the repos

resource: repository
where:
  # criteria can be provided to limit the repositories the policy is applied to
configuration:
  mandatoryFiles:
    issueTitle: This repo is missing mandatory files
    issueBody: |
      There are several mandatory files we require in this
      repository. A pull request has been opened to add the
      missing files. When the pr is merged this issue will be
      closed automatically.
    prTitle: "feat: add AVM mandatory file(s) to this repo"
    prBody: |
      This repository needs the standard workflow and policy files to ensure compliance.
    file:
      - path: .github/workflows/version-check.yml
        prContentLink: https://raw.githubusercontent.com/Azure/terraform-azurerm-avm-template/main/.github/workflows/version-check.yml
      - path: .github/workflows/linting.yml
        prContentLink: https://raw.githubusercontent.com/Azure/terraform-azurerm-avm-template/main/.github/workflows/linting.yml
      - path: Makefile
        prContentLink: https://raw.githubusercontent.com/Azure/terraform-azurerm-avm-template/main/Makefile
      - path: .github/policies/avmrequiredfiles.yml
        prContentLink: https://raw.githubusercontent.com/Azure/terraform-azurerm-avm-template/main/.github/policies/avmrequiredfiles.yml
      - path: .github/policies/branchprotection.yml
        prContentLink: https://raw.githubusercontent.com/Azure/terraform-azurerm-avm-template/main/.github/policies/branchprotection.yml
