---
version: 2

updates:
  - package-ecosystem: gomod
    directory: /tests
    schedule:
      interval: daily
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: daily