name: AVM - General Question/Feedback ❔
description: Just got a question or some general feedback? Let us know!
title: "[AVM Question/Feedback]: "
labels:
  [
    "Language: Terraform :globe_with_meridians:",
    "Type: Question/Feedback :raising_hand:",
    "Needs: Triage :mag:",
  ]
projects: ["Azure/538"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your question/feedback!

        > **NOTE**: If your question/request is related to the AVM site/documentation, please file an issue in the [AVM repo](https://github.com/Azure/Azure-Verified-Modules/issues/new?assignees=&labels=Type%3A+Question%2FFeedback+%3Araising_hand%3A%2CNeeds%3A+Triage+%3Amag%3A&projects=&template=question_feedback.yml&title=%5BQuestion%2FFeedback%5D%3A+).
  - type: checkboxes
    id: existing-checks
    attributes:
      label: Check for previous/existing GitHub issues
      description: By submitting this issue, you confirm that you have searched for previous/existing GitHub issues to avoid creating a duplicate.
      options:
        - label: I have checked for previous/existing GitHub issues
          required: true
  - type: textarea
    id: question-feedback-text
    attributes:
      label: Description
      description: Let us know your question or feedback here!
    validations:
      required: true