---
  name: test examples
  on:
    pull_request:
      types: ['opened', 'reopened', 'synchronize']
    merge_group:
    workflow_dispatch:
  
  jobs:
    check:
      runs-on: ubuntu-latest
      steps:
        - name: Checking for Fork
          shell: pwsh
          run: |
            $isFork = "${{ github.event.pull_request.head.repo.fork }}"
            if($isFork -eq "true") {
              echo "### WARNING: This workflow is disabled for forked repositories. Please follow the [release branch process](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/terraform-contribution-flow/#5-create-a-pull-request-to-the-upstream-repository) if end to end tests are required." >> $env:GITHUB_STEP_SUMMARY
            }

    run-e2e-tests:
      if: github.event.repository.name != 'terraform-azurerm-avm-template' && github.event.pull_request.head.repo.fork == false
      uses: Azure/terraform-azurerm-avm-template/.github/workflows/test-examples-template.yml@main
      name: end to end
      secrets: inherit
      permissions:
        id-token: write
        contents: read
  