---
name: linting

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: linting-${{ github.event.pull_request.head.repo.full_name }}/${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linting:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: check docs
        uses: Azure/terraform-azurerm-avm-template/.github/actions/docs-check@main

      - name: lint terraform
        uses: Azure/terraform-azurerm-avm-template/.github/actions/linting@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
