---
name: linting

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: linting-${{ github.event.pull_request.head.repo.full_name }}/${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docs:
    if: github.event.repository.name != 'terraform-azurerm-avm-template'
    name: docs
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7

      - name: check docs
        uses: Azure/terraform-azurerm-avm-template/.github/actions/docs-check@main

  terraform:
    if: github.event.repository.name != 'terraform-azurerm-avm-template'
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7

      - name: lint terraform
        uses: Azure/terraform-azurerm-avm-template/.github/actions/linting@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  avmfix:
    if: github.event.repository.name != 'terraform-azurerm-avm-template'
    name: avmfix
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7

      - name: avmfix
        uses: Azure/terraform-azurerm-avm-template/.github/actions/avmfix@main

  lintcomplete:
    needs: [docs, terraform, avmfix]
    runs-on: ubuntu-latest
    steps:
      - run: echo "All linting checks passed"
