---
name: version-check

on:
  workflow_dispatch:
  merge_group:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  version-check:
    if: github.event.repository.name != 'terraform-azurerm-avm-template'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 #v4.1.2
      - name: Check version
        uses: Azure/terraform-azurerm-avm-template/.github/actions/version-check@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
