---
name: version-check

on:
  workflow_dispatch:
  merge_group:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check version
        uses: Azure/terraform-azurerm-avm-template/.github/actions/version-check@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
